Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"  # Use an Ubuntu 18.04 box
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.provider "virtualbox"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python3 python3-pip redis-server
    pip3 install Flask redis
  SHELL
end
