apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-limiter-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rate-limiter-app
  template:
    metadata:
      labels:
        app: rate-limiter-app
    spec:
      containers:
        - name: rate-limiter-app
          image: moukthikavuyyuru/monolith-app:latest
          ports:
            - containerPort: 5500
---
apiVersion: v1
kind: Service
metadata:
  name: rate-limiter-app
spec:
  selector:
    app: rate-limiter-app
  ports:
    - protocol: TCP
      port: 5500
      targetPort: 5500
  type: LoadBalancer  # Use LoadBalancer to expose externally in Minikube
